### ISSUE TITLE
Bug with inventory data

### ISSUE THREAD

**Issue by Soulivan71** [BIG-Games-LLC/ps99-public-api-docs#75]
When Im log in and clic on dashboard to see my inventory have no acces.
![image](https://github.com/user-attachments/assets/4994260c-6204-498a-9ca1-ecea14ce99b4)

Im in tradingplaza (idk if its the issue)

But I can still acess with my userid : https://db.biggames.io/player/201444514

**Comment by Soulivan71** [comment]
@chickenputty

**Comment by Vinsterplays** [comment]
this is also happening to me when on the dashboard. Using the userid works fine

**Comment by chickenputty** [comment]
Fixed, thank you

**Comment by Soulivan71** [comment]
Seems not fix for men need to wait ?

**Comment by Vinsterplays** [comment]
yeah also not fixed for me

**Comment by WebDevTrop** [comment]
This should be fixed now, please let me know if there's any issues.

**Comment by Soulivan71** [comment]
Yes its

**Comment by Soulivan71** [comment]
> This should be fixed now, please let me know if there's any issues.

Have other issue : 
The titanic kitsune pink still not be display.
I think the site is quite laggy no ?
I can't see in real time my inventory since 2days

**Comment by Soulivan71** [comment]
I see ur doing a lot of changes, but I don't know if really good..

**Comment by WebDevTrop** [comment]
> I see ur doing a lot of changes, but I don't know if really good..

Hi, is your titanic kitsune in your inventory or in a box? 

also, what developments to the dashboard haven't been so great?

**Comment by Soulivan71** [comment]
>also, what developments to the dashboard haven't been so great?
I don't know but the display isn't really so good like there is a big black part idk if u can put more on a page etc can be cool
![image](https://github.com/user-attachments/assets/c10616ba-383c-471a-9777-b711bd3adb1b)
Like a filter/an option to display all the inventory on a single page.
And my titanic kitsune isn't in abox, is in my inventory yes and not lock

**Comment by Soulivan71** [comment]
Other thing can u add option to right clic and open in new tab etc on all buttons ?
I do red things (but basically everything on the page can be add to newtab)
![image](https://github.com/user-attachments/assets/f33b88ad-6768-4c79-a2db-5fcc3edaf872)

**Comment by WebDevTrop** [comment]
> > also, what developments to the dashboard haven't been so great?
> > I don't know but the display isn't really so good like there is a big black part idk if u can put more on a page etc can be cool
> > ![image](https://private-user-images.githubusercontent.com/36502190/374951806-c10616ba-383c-471a-9777-b711bd3adb1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzY0NDYsIm5iZiI6MTcyODQ3NjE0NiwicGF0aCI6Ii8zNjUwMjE5MC8zNzQ5NTE4MDYtYzEwNjE2YmEtMzgzYy00NzFhLTk3NzctYjcxMWJkM2FkYjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEyMTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOWM5MTE4YWY1YTQyOWQwZTI5ZTA1NzMyOTU3MWNmZGUwMzM4MmE1MDZhOTFjYTA4YjMzNjY3MWFiNWE3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OOv7tUh-LsAtllJrTrT3uYXq5ELQZnbsmmu-HOwlY50)
> > Like a filter/an option to display all the inventory on a single page.
> > And my titanic kitsune isn't in abox, is in my inventory yes and not lock

Hi, 

The only reason we have to paginate is because of the intensity of the animations that run on shiny pets. We can increase this to a larger number, however. Your UI doesn't look quite right in this, something isn't quite right. We will look into this.

**Comment by Soulivan71** [comment]
"The only reason we have to paginate is because of the intensity of the animations that run on shiny pets"
Can u maybe add a icon to indicate its shiny instead to avoid animation/lag ?

**Comment by Soulivan71** [comment]
Nice I see yes it cool
Any idea for my titanic though ?
And can u add things ? cf -> #78

**Comment by Soulivan71** [comment]
Not anymore no, but display issue with pet down page :
![image](https://github.com/user-attachments/assets/8aa24f74-bc16-403a-9bd7-22568bb7be2b)
And my titanic still display like this :
![Uploading image.png…]()

**Comment by Soulivan71** [comment]
Another issue screen moving

https://github.com/user-attachments/assets/c59594c5-d32a-47a2-b826-b473fb2afd33
